Task/v2/bugfix foreignkey
uasoft-indonesia/badaso pull request #744
Opened 2022-08-12 08:06 UTC by miftahurrahmi

2022-08-14 10:51 UTC, rizkiheryandi requested changes

2022-08-14 10:51 UTC, rizkiheryandi commented on src/ContentManager/FileGenerator.php
> +        // dd($schema_up);
please remove the testing code before pushig to the repo

2022-08-15 03:28 UTC, miftahurrahmi commented on src/ContentManager/FileGenerator.php
> +        // dd($schema_up);
ok, thank you

2022-08-18 05:55 UTC, rizkiheryandi approved these changes

2022-08-18 05:57 UTC, merged